// SPDX-License-Identifier: Apache-2.0
#include "beast/codegen_server_python.hpp"
#include "openapi.hpp"
#include "openapi3.hpp"
#include <algorithm>
#include <fstream>

namespace codegen {

void BeastServerPythonGenerator::operator()(const CodegenArgs& args, const std::filesystem::path& output_dir) {
	if (!args.spec || !args.endpoints || args.endpoints->empty()) {
		return;
	}

	module_name_ = args.module_name;
	const auto& endpoints = *args.endpoints;

	std::filesystem::create_directories(output_dir);
	auto py_path = output_dir / filenames::SERVER_PY;
	std::ofstream out(py_path);
	if (out) {
		emitServerPy(out, endpoints);
	}
}

void BeastServerPythonGenerator::emitServerPy(std::ostream& out, const std::vector<Endpoint>& endpoints) {
	out << "// Auto-generated Python server bindings\n";
	out << "// Generated by siesta-generator\n";
	out << "\n";
	out << "#include <nanobind/nanobind.h>\n";
	out << "#include <nanobind/stl/string.h>\n";
	out << "#include <nanobind/stl/vector.h>\n";
	out << "#include <nanobind/stl/shared_ptr.h>\n";
	out << "#include <nanobind/trampoline.h>\n";
	out << "\n";
	out << "#include <boost/asio.hpp>\n";
	out << "#include <boost/asio/ip/address.hpp>\n";
	out << "#include <boost/beast/core.hpp>\n";
	out << "#include <boost/beast/http.hpp>\n";
	out << "#include <boost/beast/http/field.hpp>\n";
	out << "#include <thread>\n";
	out << "\n";
	out << "#include \"server.hpp\"\n";
	out << "\n";
	out << "namespace nb = nanobind;\n";
	out << "namespace http = ::boost::beast::http;\n";
	out << "\n";
	out << "namespace {\n";
	out << "\n";
	out << "// Convert an HTTP request to a Python dict\n";
	out << "nb::dict request_to_dict(const openapi::Server::request& req) {\n";
	out << "\tnb::dict d;\n";
	out << "\t{\n";
	out << "\t\tstd::string tmp = std::string(req.method_string());\n";
	out << "\t\td[\"method\"] = nb::str(tmp.c_str(), tmp.size());\n";
	out << "\t}\n";
	out << "\t{\n";
	out << "\t\tstd::string tmp = std::string(req.target());\n";
	out << "\t\td[\"target\"] = nb::str(tmp.c_str(), tmp.size());\n";
	out << "\t}\n";
	out << "\td[\"body\"] = nb::str(req.body().c_str(), req.body().size());\n";
	out << "\tnb::dict headers;\n";
	out << "\tfor (const auto& h : req) {\n";
	out << "\t\tstd::string key(h.name_string());\n";
	out << "\t\tstd::string val(h.value());\n";
	out << "\t\theaders[nb::str(key.c_str(), key.size())] = nb::str(val.c_str(), val.size());\n";
	out << "\t}\n";
	out << "\td[\"headers\"] = std::move(headers);\n";
	out << "\treturn d;\n";
	out << "}\n";
	out << "\n";
	out << "// Write a Python object as a JSON HTTP response\n";
	out << "void write_json_response(const openapi::Server::Session::Ptr& session, const nb::object& result) {\n";
	out << "\tauto& resp = session->get_response();\n";
	out << "\ttry {\n";
	out << "\t\tnb::object json_mod = nb::module_::import_(\"json\");\n";
	out << "\t\tnb::str body = nb::cast<nb::str>(json_mod.attr(\"dumps\")(result));\n";
	out << "\t\tresp.body() = nb::cast<std::string>(body);\n";
	out << "\t\tresp.result(http::status::ok);\n";
	out << "\t\tresp.set(http::field::content_type, \"application/json\");\n";
	out << "\t\tresp.prepare_payload();\n";
	out << "\t} catch (const std::exception& e) {\n";
	out << "\t\tresp.result(http::status::internal_server_error);\n";
	out << "\t\tresp.body() = std::string(\"{\\\"error\\\":\\\"\") + e.what() + \"\\\"}\";\n";
	out << "\t\tresp.set(http::field::content_type, \"application/json\");\n";
	out << "\t\tresp.prepare_payload();\n";
	out << "\t}\n";
	out << "\tsession->write();\n";
	out << "}\n";
	out << "\n";
	out << "} // anonymous namespace\n";
	out << "\n";

	out << "namespace _siesta_detail { struct ServerCtx { boost::asio::io_context ctx; }; }\n";
	out << "\n";

	out << "struct PyServer : _siesta_detail::ServerCtx, openapi::Server {\n";
	out << "\tNB_TRAMPOLINE(Server, " << endpoints.size() << ");\n";
	out << "\tstd::thread _thread;\n";
	out << "\n";
	out << "\tPyServer() : openapi::Server(ctx) {}\n";
	out << "\t~PyServer() {\n";
	out << "\t\tctx.stop();\n";
	out << "\t\tif (_thread.joinable()) _thread.join();\n";
	out << "\t}\n";
	out << "\n";
	out << "\tvoid listen(std::string host, uint16_t port) {\n";
	out << "\t\topenapi::Server::start(boost::asio::ip::make_address(host), port);\n";
	out << "\t\t_thread = std::thread([this] { ctx.run(); });\n";
	out << "\t}\n";
	out << "\tvoid shutdown() {\n";
	out << "\t\tctx.stop();\n";
	out << "\t\tif (_thread.joinable()) _thread.join();\n";
	out << "\t}\n";
	out << "\n";

	for (const auto& ep : endpoints) {
		if (!ep.summary.empty()) {
			write_multiline_comment(out, ep.summary, "\t");
		}
		out << "\tvoid " << ep.function_name << "(const request req, Session::Ptr session) override {\n";
		out << "\t\t{\n";
		out << "\t\t\tnb::gil_scoped_acquire gil;\n";
		out << "\t\t\tnb::detail::ticket nb_ticket(nb_trampoline, \"" << ep.function_name << "\", false);\n";
		out << "\t\t\tif (nb_ticket.key.is_valid()) {\n";
		out << "\t\t\t\ttry {\n";
		out << "\t\t\t\t\tnb::object result = nb_trampoline.base().attr(nb_ticket.key)(request_to_dict(req));\n";
		out << "\t\t\t\t\twrite_json_response(session, std::move(result));\n";
		out << "\t\t\t\t} catch (const std::exception& e) {\n";
		out << "\t\t\t\t\tauto& resp = session->get_response();\n";
		out << "\t\t\t\t\tresp.result(http::status::internal_server_error);\n";
		out << "\t\t\t\t\tresp.body() = std::string(\"{\\\"error\\\":\\\"\") + e.what() + \"\\\"}\";\n";
		out << "\t\t\t\t\tresp.set(http::field::content_type, \"application/json\");\n";
		out << "\t\t\t\t\tresp.prepare_payload();\n";
		out << "\t\t\t\t\tsession->write();\n";
		out << "\t\t\t\t}\n";
		out << "\t\t\t\treturn;\n";
		out << "\t\t\t}\n";
		out << "\t\t}\n";
		out << "\t\tauto& resp = session->get_response();\n";
		out << "\t\tresp.result(http::status::not_implemented);\n";
		out << "\t\tsession->write();\n";
		out << "\t}\n";
		out << "\n";
	}

	out << "}; // PyServer\n";
	out << "\n";

	out << "NB_MODULE(" << module_name_ << ", m) {\n";
	out << "\tm.doc() = \"Siesta-generated Python server bindings\";\n";
	out << "\tnb::class_<openapi::Server, PyServer>(m, \"Server\")\n";
	out << "\t\t.def(nb::init<>())\n";
	out << "\t\t.def(\"listen\", [](openapi::Server& s, std::string host, uint16_t port) {\n";
	out << "\t\t\tstatic_cast<PyServer&>(s).listen(std::move(host), port);\n";
	out << "\t\t}, nb::arg(\"host\") = std::string(\"localhost\"), nb::arg(\"port\") = 443)\n";
	out << "\t\t.def(\"shutdown\", [](openapi::Server& s) { static_cast<PyServer&>(s).shutdown(); });\n";
	out << "}\n";
}

} // namespace codegen
