// SPDX-License-Identifier: Apache-2.0
#pragma once
/// Shared runtime utilities for nanobind Python extension modules
/// generated by siesta-generator.  Include this in your CMakeLists.txt
/// target include path (it lives under siesta/beast/).

#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/optional.h>
#include <nanobind/stl/variant.h>
#include <nanobind/stl/vector.h>
#include <nanobind/stl/shared_ptr.h>

#include <boost/json.hpp>
#include <stdexcept>

#include <siesta/beast/client.hpp>

namespace nb = nanobind;

namespace siesta::beast::py {

// Convert boost::json::value to a Python object (recursive)
inline nb::object json_to_python(const boost::json::value& jv) {
	try {
		switch (jv.kind()) {
		case boost::json::kind::null:
			return nb::none();
		case boost::json::kind::bool_:
			return nb::bool_(jv.get_bool());
		case boost::json::kind::int64:
			return nb::int_(jv.get_int64());
		case boost::json::kind::uint64:
			return nb::int_(jv.get_uint64());
		case boost::json::kind::double_:
			return nb::float_(jv.get_double());
		case boost::json::kind::string:
			return nb::str(jv.as_string().data());
		case boost::json::kind::array: {
			nb::list py_list;
			for (const auto& elem : jv.get_array()) {
				py_list.append(json_to_python(elem));
			}
			return py_list;
		}
		case boost::json::kind::object: {
			nb::dict py_dict;
			for (const auto& member : jv.get_object()) {
				py_dict[nb::str(member.key().data())] = json_to_python(member.value());
			}
			return py_dict;
		}
		default:
			return nb::str("<unknown json type>");
		}
	} catch (const std::exception& e) {
		return nb::str("<json conversion error: ") + nb::str(e.what()) + nb::str(">");
	}
}

// Extract JSON body from an HTTP outcome and convert to Python
inline nb::object extract_response_json(const ::siesta::beast::ClientBase::outcome_type& outcome) {
	try {
		const auto& response = outcome.value();
		const auto& body = response.body();
		if (body.empty()) {
			return nb::dict();
		}
		boost::system::error_code ec;
		auto jv = boost::json::parse(body, ec);
		if (ec) {
			return nb::str(body.c_str());
		}
		return json_to_python(jv);
	} catch (const std::exception& e) {
		nb::dict err;
		err["error"] = nb::str(e.what());
		return err;
	}
}

} // namespace siesta::beast::py
