// SPDX-License-Identifier: Apache-2.0
#include "codegen_python.hpp"
#include "openapi.hpp"
#include "openapi3.hpp"
#include <algorithm>
#include <fstream>

namespace codegen {

void PythonGenerator::operator()(const CodegenArgs& args, const std::filesystem::path& output_dir) {
	if (!args.spec || !args.endpoints || args.endpoints->empty()) {
		return;
	}

	module_name_ = args.module_name;

	std::filesystem::create_directories(output_dir);
	auto py_path = output_dir / "py_module.cpp";
	std::ofstream out(py_path);
	if (!out) {
		return;
	}

	emitModulePreamble(out, module_name_);
	emitModuleBody(out, *args.endpoints);
}

void PythonGenerator::emitModulePreamble(std::ostream& out, const std::string& module_name) {
	out << "// Auto-generated Python extension module\n";
	out << "// Generated by siesta-generator\n";
	out << "//\n";
	out << "// Build instructions:\n";
	out << "//   1. Ensure nanobind is available (find_package(nanobind 2.12 REQUIRED))\n";
	out << "//   2. Link against siesta, boost::json, boost::system\n";
	out << "//   3. Use: nanobind_add_module(" << module_name << " " << module_name << ".cpp)\n";
	out << "\n";
	out << "#include <nanobind/nanobind.h>\n";
	out << "#include <nanobind/stl/string.h>\n";
	out << "#include <nanobind/stl/optional.h>\n";
	out << "#include <nanobind/stl/variant.h>\n";
	out << "#include <nanobind/stl/vector.h>\n";
	out << "#include <nanobind/stl/shared_ptr.h>\n";
	out << "\n";
	out << "#include <boost/asio/use_future.hpp>\n";
	out << "#include <boost/json.hpp>\n";
	out << "#include <future>\n";
	out << "\n";
	out << "#include <siesta/beast/python_util.hpp>\n";
	out << "#include \"client.hpp\"\n";
	out << "#include \"openapi_defs.hpp\"\n";
	out << "\n";
	out << "namespace nb = nanobind;\n";
	out << "using namespace siesta::beast::py;\n";
	out << "\n";
}

void PythonGenerator::emitEndpointWrapper(std::ostream& out, const Endpoint& ep, bool is_last) {
	out << "\t\t.def(\"" << ep.function_name << "\",\n";
	out << "\t\t\t[](ClientWrapper& self";

	if (ep.has_request_body) {
		out << ", const " << ep.body_type << "& body";
	}

	for (size_t i = 0; i < ep.params.size(); ++i) {
		out << ", ";
		const auto& param = ep.params[i];
		if (!param.required) {
			out << "std::optional<" << param.cpp_type << "> " << param.name;
		} else {
			out << param.cpp_type << " " << param.name;
		}
	}

	out << ") -> nb::object {\n";

	out << "\t\tboost::asio::io_context& ctx = self.ctx;\n";

	out << "\t\ttry {\n";

	out << "\t\t\tauto future = self.client->" << ep.function_name << "(";

	bool has_previous = false;
	if (ep.has_request_body) {
		out << "body";
		has_previous = true;
	}
	for (size_t i = 0; i < ep.params.size(); ++i) {
		if (has_previous) {
			out << ", ";
		}
		out << ep.params[i].name;
		has_previous = true;
	}

	if (has_previous) {
		out << ", ";
	}
	out << "boost::asio::use_future);\n";

	out << "\t\t\tctx.restart();\n";
	out << "\t\t\tctx.run();\n";

	out << "\t\t\tauto outcome = future.get();\n";

	out << "\t\t\treturn extract_response_json(outcome);\n";

	out << "\t\t} catch (const std::exception& e) {\n";
	out << "\t\t\tnb::dict err;\n";
	out << "\t\t\terr[\"error\"] = nb::str(e.what());\n";
	out << "\t\t\treturn err;\n";
	out << "\t\t}\n";

	std::string doc = ep.description.empty() ? ep.summary : ep.description;
	bool has_trailing = ep.has_request_body || !ep.params.empty() || !doc.empty();

	if (has_trailing) {
		out << "\t\t},\n";
	} else if (is_last) {
		out << "\t\t});\n";
	} else {
		out << "\t\t),\n";
	}

	if (ep.has_request_body || !ep.params.empty()) {
		out << "\t\t";
		bool first = true;
		if (ep.has_request_body) {
			out << "nb::arg(\"body\")";
			first = false;
		}
		for (size_t i = 0; i < ep.params.size(); ++i) {
			if (!first)
				out << ", ";
			out << "nb::arg(\"" << ep.params[i].name << "\")";
			if (!ep.params[i].required) {
				out << " = nb::none()";
			}
			first = false;
		}
		out << ",\n";
	}

	if (!doc.empty()) {
		std::string escaped_doc;
		for (char c : doc) {
			if (c == '"')
				escaped_doc += "\\\"";
			else if (c == '\\')
				escaped_doc += "\\\\";
			else if (c == '\n')
				escaped_doc += "\\n";
			else
				escaped_doc += c;
		}
		out << "\t\t\"" << escaped_doc << "\"\n";
	}

	if (has_trailing) {
		if (is_last) {
			out << "\t\t);\n";
		} else {
			out << "\t\t)\n";
		}
	}
}

void PythonGenerator::emitModuleBody(std::ostream& out, const std::vector<Endpoint>& endpoints) {
	AuthType auth_type = AuthType::None;
	std::string auth_member_name;
	std::string auth_param_name;
	for (const auto& ep : endpoints) {
		if (ep.auth_type != AuthType::None) {
			auth_type = ep.auth_type;
			if (auth_type == AuthType::ApiKey) {
				auth_member_name = "api_key";
				auth_param_name = "api_key";
			} else if (auth_type == AuthType::HttpBearer) {
				auth_member_name = "bearer_token";
				auth_param_name = "bearer_token";
			}
			break;
		}
	}

	out << "// Python extension module definition\n";
	out << "// The module name should match the shared library name (e.g., Echo_API.so -> Echo_API)\n";
	out << "\n";

	out << "struct ClientWrapper {\n";
	out << "\tboost::asio::io_context ctx;\n";
	out << "\tstd::shared_ptr<openapi::Client> client;\n";
	if (auth_type != AuthType::None) {
		out << "\tClientWrapper(std::string host = \"localhost\", uint16_t port = 443, std::string " << auth_param_name
			<< " = \"\")\n";
		out << "\t\t: client(std::make_shared<openapi::Client>(ctx, std::move(" << auth_param_name << "))) {\n";
	} else {
		out << "\tClientWrapper(std::string host = \"localhost\", uint16_t port = 443)\n";
		out << "\t\t: client(std::make_shared<openapi::Client>(ctx)) {\n";
	}
	out << "\t\tclient->start(boost::asio::ip::make_address(host), port);\n";
	out << "\t\tctx.run();\n";
	out << "\t}\n";
	out << "\t~ClientWrapper() { client->stop(); }\n";
	out << "\tauto& context() { return ctx; }\n";
	out << "\tvoid start(std::string host, uint16_t port) {\n";
	out << "\t\tclient->stop();\n";
	out << "\t\tclient->start(boost::asio::ip::make_address(host), port);\n";
	out << "\t\tctx.restart();\n";
	out << "\t\tctx.run();\n";
	out << "\t}\n";
	out << "\tvoid stop() { client->stop(); }\n";
	out << "};\n";
	out << "\n";

	out << "NB_MODULE(" << module_name_ << ", m) {\n";
	out << "\tm.doc() = \"Siesta-generated Python bindings for OpenAPI client\";\n";
	out << "\n";
	out << "\t// Client class wrapping the C++ siesta client\n";
	if (auth_type != AuthType::None) {
		out << "\tnb::class_<ClientWrapper>(m, \"Client\")\n";
		out << "\t\t.def(nb::init<std::string, uint16_t, std::string>(), nb::arg(\"host\") = std::string(\"localhost\"), "
			   "nb::arg(\"port\") = 443, nb::arg(\"" << auth_param_name << "\") = std::string(\"\"))\n";
	} else {
		out << "\tnb::class_<ClientWrapper>(m, \"Client\")\n";
		out << "\t\t.def(nb::init<std::string, uint16_t>(), nb::arg(\"host\") = std::string(\"localhost\"), "
			   "nb::arg(\"port\") = 443)\n";
	}
	out << "\t\t.def(\"start\", &ClientWrapper::start, nb::arg(\"host\"), nb::arg(\"port\"))\n";
	out << "\t\t.def(\"stop\", &ClientWrapper::stop)\n";

	for (size_t i = 0; i < endpoints.size(); ++i) {
		out << "\n";
		emitEndpointWrapper(out, endpoints[i], i == endpoints.size() - 1);
	}

	out << "}\n";
}

} // namespace codegen
